---
name: Sys-Sendfile
version: 0.04
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Zero-copy data transfer
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Sys-Sendfile
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
provides:
  Sys::Sendfile:
    file: lib/Sys/Sendfile.pm
    version: 0.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - sendfile
  - zero-copy
