---
abstract: 'Zero-copy data transfer'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  Fcntl: 0
  File::Spec: 0
  IO::Handle: 0
  IO::Socket::INET: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Sendfile
provides:
  Sys::Sendfile:
    file: lib/Sys/Sendfile.pm
    version: 0.12
requires:
  Exporter: 5.57
  XSLoader: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Sys-Sendfile
  repository: git://github.com/Leont/sys-sendfile.git
version: 0.12
