---
name: Sys-Sendfile
version: 0.10
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Zero-copy data transfer
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Sys-Sendfile
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/sys-sendfile
requires:
  perl: 5.006
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
provides:
  Sys::Sendfile:
    file: lib/Sys/Sendfile.pm
    version: 0.10
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - sendfile
  - zero-copy
